### ISSUE TITLE
Przetworzenie danych

### ISSUE THREAD

**Issue by Ihoold** [Ihoold/DataProducts#5]
Przygotowanie danych do przedstawienia w formie wizualnej

**Comment by Wesmania** [comment]
Dane są przetwarzane w tej chwili poprzez funkcje globalne, ale jest już na czym pracować.
Wyniki dzielone są wg. płci, szkoły, wyników poprzednich egzaminów. Pozostaje opakować funkcje w pakiet, w przyszłości może coś do nich dodamy.

**Comment by Wesmania** [comment]
Funkcje do przetwarzania danych są opakowane w ładny pakiet. Przyszłe zmiany to już tylko zmiany zakresu / metodyki.
